[project]
name = "fintrack-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "gpt4all[cuda]>=2.8.2",
    "uvicorn>=0.34.2",
]
